'use strict';
const D=window.CONTROL_MAP,$=s=>document.querySelector(s),NS='http://www.w3.org/2000/svg';
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nodes=D.nodes.filter(n=>n.id!=='controller').map(n=>({...n,r:n.signer?48:n.type==='safe'?68:n.type==='governance'?63:55}));
const by=Object.fromEntries(nodes.map(n=>[n.id,n])),edges=D.edges.filter(e=>e.status!=='proposed'),sources=Object.fromEntries(D.sources.map(s=>[s.id,s]));
const pos={gov:[250,160],timelock:[500,180],admin:[520,530],upgrade:[890,560],tmc:[1270,680],community:[1260,280],comet:[270,720],config:[480,850],proxyadmin:[730,840],treasury:[1060,970],escrow:[1390,1010],avatar:[970,1160],fd947:[650,720],FC63:[960,340],'0660':[720,400],'671b':[520,340],d2A7:[1110,460],FcFf:[910,760],'9963':[1070,770],aA9D:[1510,660],'66cD':[1500,810],f5e6:[1520,960],'55be':[1460,110],'4A3a':[1590,260],a1bB:[1590,410],'9A73':[1190,85],'46B3':[1040,90],'7e4A':[1450,340],'2B38':[1500,495],B8Dc:[630,1050],'3d0e':[460,1070],foundation:[270,350],cgwg:[800,110],security:[1780,370]};
nodes.forEach(n=>{[n.x,n.y]=pos[n.id];});
const short=a=>a.slice(0,6)+'…'+a.slice(-4);
let selected=null,hover=null,t={x:0,y:0,k:1},drag=null,moved=false;
function el(tag,attrs,parent){const e=document.createElementNS(NS,tag);Object.entries(attrs||{}).forEach(([k,v])=>e.setAttribute(k,v));if(parent)parent.appendChild(e);return e;}
function lines(label){if(label==='compound-dao.eth')return ['compound-','dao.eth'];const out=[];let l='';label.split(' ').forEach(w=>{if((l+' '+w).trim().length>13&&l){out.push(l);l=w;}else l+=(l?' ':'')+w;});if(l)out.push(l);return out;}
edges.forEach(e=>{e.path=el('path',{class:'edge '+e.status,'marker-end':'url(#arrow)'},$('#edges'));e.hit=el('path',{class:'edge-hit'},$('#edges'));el('title',{},e.hit).textContent=by[e.from].label+' → '+by[e.to].label+': '+e.label;e.hit.addEventListener('pointerdown',ev=>{ev.stopPropagation();moved=false;});e.hit.addEventListener('click',ev=>{ev.stopPropagation();if(!moved)showEdge(e);});e.hit.addEventListener('mouseenter',()=>{if(!drag){hover=e;highlight();}});e.hit.addEventListener('mouseleave',()=>{hover=null;highlight();});});
nodes.forEach(n=>{const g=el('g',{class:'bubble '+n.type,role:'button',tabindex:'0','aria-label':n.label+(n.threshold?' · '+n.threshold+' of '+(n.owners?.length||1):''),'data-node':n.id},$('#bubbles'));n.g=g;el('circle',{r:n.r},g);const ls=lines(n.label.replace('Unattributed · ','Unknown ')),base=-(ls.length-1)*8-(n.threshold||n.signer?6:0);ls.forEach((l,i)=>el('text',{y:base+i*17,'dominant-baseline':'middle'},g).textContent=l);if(n.threshold||n.signer)el('text',{class:'sub',y:base+ls.length*17+3,'dominant-baseline':'middle'},g).textContent=n.threshold?n.threshold+' / '+(n.owners?.length||1):n.status==='unknown'?short(n.address):'documented';g.addEventListener('click',e=>e.stopPropagation());g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(n.id);}});g.addEventListener('mouseenter',()=>{if(!drag){hover=n.id;highlight();}});g.addEventListener('mouseleave',()=>{hover=null;highlight();});g.addEventListener('pointerdown',e=>startDrag(e,n));});
function paint(){nodes.forEach(n=>n.g.setAttribute('transform',`translate(${n.x},${n.y})`));edges.forEach(e=>{const a=by[e.from],b=by[e.to],dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||1,d=`M${a.x+dx/l*(a.r+3)},${a.y+dy/l*(a.r+3)} L${b.x-dx/l*(b.r+5)},${b.y-dy/l*(b.r+5)}`;e.path.setAttribute('d',d);e.hit.setAttribute('d',d);});highlight();}
function highlight(){const id=typeof hover==='string'?hover:selected,fe=hover&&typeof hover==='object'?hover:null,c=new Set(id?[id]:[]);edges.forEach(e=>{if(e.from===id)c.add(e.to);if(e.to===id)c.add(e.from);});if(fe){c.clear();c.add(fe.from);c.add(fe.to);}nodes.forEach(n=>n.g.setAttribute('class','bubble '+n.type+(n.id===selected?' selected':'')+((id||fe)&&!c.has(n.id)?' faded':'')));$('#edge-labels').replaceChildren();edges.forEach(e=>{const active=fe?e===fe:id&&(e.from===id||e.to===id);e.path.setAttribute('class','edge '+e.status+((id||fe)&&!active?' faded':'')+(active?' lit':''));if(active){const a=by[e.from],b=by[e.to];el('text',{class:'edge-label',x:(a.x+b.x)/2,y:(a.y+b.y)/2-7},$('#edge-labels')).textContent=e.type==='signer-of'?'signer':e.type==='missing-direct-revocation-path'?'no direct route identified':e.label;}});}
function sourceList(ids){return [...new Set(ids)].filter(id=>sources[id]).map(id=>`<a href="${safe(sources[id].url)}" target="_blank" rel="noopener noreferrer">${safe(sources[id].title)} ↗</a>`).join('');}
function panel(html){$('#detail').innerHTML='<button class="close" aria-label="Close details">×</button>'+html;$('#detail').hidden=false;$('#detail .close').onclick=clear;$('#detail').scrollTop=0;}
function select(id){selected=id;hover=null;const n=by[id],related=edges.filter(e=>e.from===id||e.to===id);panel(`<span class="tag">${n.signer?(n.status==='unknown'?'IDENTITY UNKNOWN':'PUBLIC ATTRIBUTION'):n.type.toUpperCase()}</span><h2>${safe(n.label)}</h2>${n.address?`<a class="address" href="https://etherscan.io/address/${n.address}" target="_blank" rel="noopener noreferrer">${n.address} ↗</a>`:''}${n.threshold?`<p>${n.threshold} of ${n.owners?.length||1} owner authorizations</p>`:''}${related.map(e=>{const other=e.from===id?e.to:e.from;return `<button class="connection" data-id="${other}">${e.from===id?'→':'←'} ${safe(by[other].label)}<small>${safe(e.label)}${e.status==='onchain'?'':' · '+e.status}</small></button>`;}).join('')}<details><summary>Evidence & notes</summary><p>${safe(n.summary)}</p><p>${safe(n.powers)}</p>${sourceList(n.sources)}</details>`);$('#detail').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>select(b.dataset.id));highlight();}
function showEdge(e){selected=null;hover=e;panel(`<span class="tag">${e.status==='onchain'?'ON-CHAIN VERIFIED':e.status.toUpperCase()}</span><h2>${safe(by[e.from].label)} → ${safe(by[e.to].label)}</h2><p>${safe(e.label)}</p><details open><summary>Sources</summary>${sourceList(e.sources)}</details>`);highlight();}
function clear(){selected=null;hover=null;$('#detail').hidden=true;highlight();}
function apply(){ $('#scene').setAttribute('transform',`translate(${t.x},${t.y}) scale(${t.k})`);}
function fit(){const b=$('#map').getBoundingClientRect(),x=Math.min(...nodes.map(n=>n.x-n.r))-55,X=Math.max(...nodes.map(n=>n.x+n.r))+55,y=Math.min(...nodes.map(n=>n.y-n.r))-55,Y=Math.max(...nodes.map(n=>n.y+n.r))+55;t.k=Math.min(b.width/(X-x),(b.height-80)/(Y-y));t.x=(b.width-(X-x)*t.k)/2-x*t.k;t.y=(b.height-60-(Y-y)*t.k)/2-y*t.k+15;apply();}
function zoom(f,x,y){const b=$('#map').getBoundingClientRect();x??=b.width/2;y??=b.height/2;const k=Math.max(.16,Math.min(3.8,t.k*f)),r=k/t.k;t.x=x-(x-t.x)*r;t.y=y-(y-t.y)*r;t.k=k;apply();}
function startDrag(e,n){if(e.button!==0)return;e.stopPropagation();moved=false;drag={n,x:e.clientX,y:e.clientY,lx:e.clientX,ly:e.clientY};$('#map').setPointerCapture(e.pointerId);}
$('#map').addEventListener('pointerdown',e=>startDrag(e,null));$('#map').addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.lx,dy=e.clientY-drag.ly;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>4)moved=true;if(moved){if(drag.n){drag.n.x+=dx/t.k;drag.n.y+=dy/t.k;paint();}else{t.x+=dx;t.y+=dy;apply();}}drag.lx=e.clientX;drag.ly=e.clientY;});$('#map').addEventListener('pointerup',()=>{const d=drag;drag=null;if(d&&!moved){if(d.n)select(d.n.id);else clear();}});$('#map').addEventListener('pointercancel',()=>drag=null);$('#map').addEventListener('wheel',e=>{e.preventDefault();const b=$('#map').getBoundingClientRect();zoom(Math.exp(-e.deltaY*.0015),e.clientX-b.left,e.clientY-b.top);},{passive:false});$('#plus').onclick=()=>zoom(1.25);$('#minus').onclick=()=>zoom(.8);$('#fit').onclick=()=>{clear();fit();};window.addEventListener('resize',fit);document.addEventListener('keydown',e=>{if(e.key==='Escape'){clear();$('#results').hidden=true;}});
$('#search').oninput=e=>{const q=e.target.value.trim().toLowerCase(),matches=nodes.filter(n=>(n.label+' '+(n.address||'')).toLowerCase().includes(q));$('#results').hidden=!q;$('#results').innerHTML=matches.length?matches.map(n=>`<button data-id="${n.id}">${safe(n.label)}</button>`).join(''):'<p>No match</p>';$('#results').querySelectorAll('button').forEach(b=>b.onclick=()=>{select(b.dataset.id);$('#results').hidden=true;$('#search').value='';});};
$('#about').onclick=()=>panel(`<span class="tag">INDEPENDENT COMMUNITY RESEARCH</span><h2>${nodes.length} bubbles. ${edges.length} connections.</h2><p>Ethereum · Observations dated 19–21 September 2026.</p><p>Solid lines: contract permissions or owner membership. Dashed lines: documented roles or inferred missing routes. Labels do not prove individual key custody.</p><p>Overlap does not imply misconduct.</p><details><summary>Research & sources</summary><a href="data.json" target="_blank">Evidence dataset ↗</a><a href="https://github.com/umersin61/compound-control-map" target="_blank" rel="noopener noreferrer">Source repository ↗</a><p>${safe(D.reviewMethod)}</p></details>`);
paint();fit();
