// Reproducible, manually reviewed evidence dataset. No remote requests.
const fs=require('fs');
const A={gov:'0x309a862bbC1A00e45506cB8A802D1ff10004c8C0',timelock:'0x6d903f6003cca6255D85CcA4D3B5E5146dC33925',admin:'0x4f05f11CA5dE8946958d58AD765f16755f23b113',upgrade:'0x76a07f14b53a205000d010af6cf96d4a41638629',tmc:'0x8BacCcA3e83843555867b3865d7689D099406567',community:'0xbbf3f1421D886E9b2c5D716B5192aC998af2012c',comet:'0x207158a267CBD2598BB3d611D8CBdEE2709F2F8C',proxyadmin:'0x362739f84fFE4e5F06395301617A90F62eE1f4cf',config:'0xd61c0169e931381fb3cC4B40316805333808c1Fa',treasury:'0xefeD08b791423C7D7937507Cf840E86a7ddC11c1',escrow:'0xDcB34b56842F853A69E86De5A0c22c49d97C130C',avatar:'0xeB6332bbB14b1488eFb3A395B8EBF6a6904C4241'};
const owners={
admin:['fd947','FC63','0660','671b'],
upgrade:['d2A7','671b','FcFf','FC63','fd947','0660','9963'],
tmc:['aA9D','fd947','66cD','f5e6','FC63','0660'],
community:['55be','4A3a','a1bB','d2A7','9A73','46B3','FC63','7e4A','2B38'],
fd947:['0660','B8Dc','3d0e']};
const signerRows=[
['fd947','0xfd947c72f09703210eeCbcab9c9206fE5e1Bb6e2','compound-dao.eth','safe','Etherscan ENS label; nested 2-of-3 Safe. The label alone does not establish authority to represent the DAO. Exact organizational attribution is unresolved.','nested'],
['FC63','0xFC63ef192E26E428f349057544a8786453C94f84','Gauntlet','organization','Publicly listed as Gauntlet’s current Community Multisig signer in the April 2026 update. The individual key custodian is not identified.','community-list'],
['0660','0x0660db80d6e5DFD9Fe168B7967B09A09328E6bF2','Unattributed · 0660','unknown','Owner on Admin, Upgrade, TMC and the nested compound-dao.eth Safe. Public person or organization attribution was not established.',''],
['671b','0x671bcF4ff02718F2eC863930D8353b045489a00A','Unattributed · 671b','unknown','Owner on Admin and Upgrade. Do not assign a Foundation or security-provider seat by elimination.',''],
['d2A7','0xd2A79F263eC55DBC7B724eCc20FC7448D4795a0C','WOOF','organization','Listed as WOOF in the current signer register; an earlier register identifies Dmytriy B. (WOOF). This is a public role attribution, not proof of present individual key custody.','community-list'],
['FcFf','0xFcFf41fe8F3BBC53562a1543c52Ec5898248800B','Unattributed · FcFf','unknown','Upgrade Safe owner. No supported public identity established.',''],
['9963','0x9963d2f9c7E416770771d1cAF8b46ef116a2085f','Unattributed · 9963','unknown','Upgrade Safe owner. No supported public identity established.',''],
['aA9D','0xaA9D81Ae677baf7fb47A1B1B89661f45CD81Fb2e','Victor · Platonia','person','The TMC transparency update identifies this owner as Victor, founder of Platonia, added on 11 June 2026.','tmc-update'],
['66cD','0x66cD62c6F8A4BB0Cd8720488BCBd1A6221B765F9','allthecolors','person','Public pseudonym. A 2022 forum post self-attests control of this exact address and allthecolors.eth. Current TMC membership is verified separately.','colors'],
['f5e6','0xf5e68cBD19d94D5e2ddEAc8db020Cae604074444','Unattributed · f5e6','unknown','TMC owner. No supported public identity established.',''],
['55be','0x55bea483873291eB3ded185c9962676F107cB4D6','ZeroShadow','organization','Current Community Multisig register identifies this organizational seat. Individual key custodian is not established.','community-list'],
['4A3a','0x4A3a60ee1007A477EDFccB7182ee7F4Ef876fa25','Certora','organization','Current Community Multisig register identifies this organizational seat.','community-list'],
['a1bB','0xa1bB2061FEbaF91738f104a19073C84589B92b53','ChainSecurity','organization','Current Community Multisig register identifies this organizational seat.','community-list'],
['9A73','0x9A73D57BB1fB280C5672A13f655675De25F13b70','PGov','organization','Current Community Multisig register identifies PGov. The CGWG renewal separately documents PGov’s membership and Community Multisig coordination role.','community-list'],
['46B3','0x46B360011A84C5759680852ed90E6Db44E18F08c','Michael Lewellen','person','Named in the September 2025 rotation and the April 2026 current register.','community-list'],
['7e4A','0x7e4A8391C728fEd9069B2962699AB416628B19Fa','0age','person','Public pseudonym in the current register. Historical Dharma affiliation is not treated as current employment.','community-list'],
['2B38','0x2B384212EDc04Ae8bB41738D05BA20E33277bf33','arr00','person','Public pseudonym in the current register. No additional personal identity inferred.','community-list'],
['B8Dc','0xB8Dcad009E533066F12e408075E10E3a30F1f15A','Juan / Juanbug','person','The June 2024 Uniswap LTIPP proposal publicly lists Juanbug with this exact address. Lido committee documentation corroborates the match. This is public attribution, not fresh proof of current key custody.','uadp'],
['3d0e','0x3d0e30031b547737fFCf13c127350159A6C4ce17','Abdullah Umar','person','The June 2024 Uniswap LTIPP proposal lists Abdullah Umar with this exact address. His January 2024 Uniswap committee application identifies Michigan Blockchain / Arana Digital. Current key custody and the organizational mandate of this Safe remain separate questions.','uadp']];
const sources=[];
function src(id,title,url,kind,note,date='2026-09-21'){sources.push({id,title,url,kind,note,accessed:date});}
Object.entries(A).forEach(([id,a])=>src(id,id==='gov'?'Compound Governor · verified contract':`${({timelock:'Governor Timelock',admin:'Admin Safe',upgrade:'Upgrade Safe',tmc:'TMC Safe',community:'Community Multisig',comet:'Institutional Comet',proxyadmin:'CometProxyAdmin',config:'Configurator',treasury:'Treasury Timelock',escrow:'Treasury escrow',avatar:'Avantgarde Avatar Safe'})[id]} · contract state`,'https://etherscan.io/address/'+a+(['admin','upgrade','tmc','community','comet','config','avatar','gov'].includes(id)?'#readProxyContract':'#readContract'),'onchain','Read-only explorer contract calls; re-run the methods listed in the evidence ledger. These URLs show current state, not a pinned historical block.', ['gov','timelock','escrow','avatar'].includes(id)?'2026-09-19':'2026-09-21'));
src('nested','compound-dao.eth · nested Safe','https://etherscan.io/address/'+signerRows[0][1]+'#readProxyContract','onchain','getOwners() and getThreshold(); ENS label displayed by explorer.');
src('community-list','Community Multisig · April 2026 signer update','https://www.comp.xyz/t/community-multisig-deployment/134/25','documented','Current public address-to-name register. Earlier posts 19, 20 and 23 provide rotation history.');
src('tmc-update','TMC transparency · Victor addition','https://www.comp.xyz/t/tmc-transparency-thread/7917/2','documented','Named address; increase from 3/5 to 4/6.');
src('tmc-transparency','TMC transparency · deployed architecture','https://www.comp.xyz/t/tmc-transparency-thread/7917','documented','Escrow, treasury timelock and external treasury strategies; statements are distinguished from live contract reads.');
src('colors','allthecolors · exact-address self-attestation','https://www.comp.xyz/t/cgp-2-0-delegated-domain-allocation-by-questbook/3352/56','documented','Public 2022 self-attestation. Signature was not independently recovered in this review.');
src('discussion','Institutional Comet · governance discussion','https://www.comp.xyz/t/transfer-ultimate-control-of-institutional-comet-to-compound-governance/8061/2','documented','Arana Digital describes launch authority, acknowledges absence of direct COMP revocation, and names institutional seat categories.');
src('transition','Institutional Comet · transition discussion','https://www.comp.xyz/t/transfer-ultimate-control-of-institutional-comet-to-compound-governance/8061/9','documented','Foundation discusses handover assessment and possible implementation constraints. A statement of intent is not a deployed control path.');
src('deployment','Institutional deployment · code review','https://github.com/Compound-Foundation/comet/pull/18/files','documented','Deployment roots and configuration; used to corroborate addresses and document pause guardian.');
src('terms','Foundation terms · launch-phase administration','https://www.compound.xyz/terms-of-service','documented','Section 3A explicitly distinguishes launch-phase market administration from Compound Governance.');
src('cgwg','CGWG renewal · roles and coordination','https://www.comp.xyz/t/renewing-the-compound-governance-working-group-cgwg-2026/7566/1','documented','Arana Digital and PGov roles, multisig coordination and Foundation cooperation. Organizational connections are not proof of common key custody.');
src('stewardship','CGWG · governance authority statement','https://www.comp.xyz/t/renewing-the-compound-governance-working-group-cgwg-2026/7566/11','documented','States that changes to the stewardship model are within governance authority; policy statement rather than an executable permission.');
src('tmc-mandate','TMC establishment · proposed architecture','https://www.comp.xyz/t/establishment-of-treasury-management-program-and-treasury-management-committee/7710','documented','Original design and committee remit. Its upgradeability description is not substituted for verification of deployed access control.');
src('zodiac','Avantgarde · governance-owned delegation proposal','https://www.comp.xyz/t/a-treasury-growth-strategy-for-compound/6205/28','documented','Proposed Avatar Safe ownership and scoped Zodiac Roles delegation. Historical design precedent, not proof that the same design is deployed for Institutional Comet.');
src('ssp','Security service providers · joint proposal','https://www.comp.xyz/t/request-for-proposal-rfp-compound-dao-security-service-provider-ssp/6955/3','documented','ChainSecurity and Certora jointly describe security responsibilities and multisig participation.');
src('resolution','Proposal 608 · governance resolution','https://www.tally.xyz/gov/compound/proposal/608?govId=eip155:1:0x309a862bbC1A00e45506cB8A802D1ff10004c8C0','documented','Resolution context. This map does not assert a current voting outcome or that a signaling vote itself changes permissions.');
src('uadp','Uniswap LTIPP · exact-address signer register','https://gov.uniswap.org/t/arbitrum-ltipp-incentive-matching/24066','documented','June 2024 proposal names Juanbug and Abdullah Umar alongside the exact addresses; public historical attribution, not fresh key-custody proof.','2026-09-22');
src('abdullah','Abdullah Umar · public Arana affiliation','https://gov.uniswap.org/t/uniswap-deployments-accountability-committee-next-steps-the-committee-application-thread/22475/5','documented','January 2024 applicant self-identification: Michigan Blockchain / Arana Digital.','2026-09-22');
src('juan','Lido committees · Juan address','https://docs.lido.fi/multisigs/committees/','documented','Corroborating exact-address public attribution.','2026-09-22');
src('comet-code','Comet core · reference source','https://github.com/Compound-Foundation/comet/blob/main/contracts/CometWithExtendedAssetList.sol','documented','Core privileged functions reviewed; repository main is mutable, not an immutable deployed-bytecode attestation.','2026-09-22');
src('config-code','Configurator · reference source','https://github.com/Compound-Foundation/comet/blob/main/contracts/Configurator.sol','documented','Configuration setters and deployment process; source-level explanation is distinct from the dated role readings.','2026-09-22');
src('escrow-code','Treasury escrow · verified source','https://etherscan.io/address/'+A.escrow+'#code','documented','Deployed verified CompoundTreasury source: withdrawal, safeguard, role replacement and revoke methods.','2026-09-22');
const nodes=[];
function node(id,label,type,summary,powers,refs,extra={}){nodes.push({id,label,type,address:A[id]||null,summary,powers,sources:refs,status:'onchain',...extra});}
node('gov','Compound Governor','governance','COMP governance proposal and voting contract.','Successful proposals can execute through the Governor Timelock, subject to voting, timelock and cancellation rules. A vote does not grant permissions that a destination contract does not recognize.',['gov'],{readDate:'2026-09-19'});
node('timelock','Governor Timelock','governance','Execution address for Compound governance.','Can exercise permissions granted to this address, including the Treasury Timelock administrator role. It is absent from the verified Admin and Upgrade Safe owner lists.',['timelock','treasury','admin','upgrade']);
node('admin','Admin Safe','safe','Institutional market administration.','Comet.governor() and Configurator.governor() point here. This Safe can authorize the administrative functions exposed by those contracts; the proxy upgrade ownership is separate.',['admin','comet','config'],{threshold:3,owners:owners.admin,modules:[],moduleDate:'2026-09-21'});
node('upgrade','Upgrade Safe','safe','Owns Institutional Comet’s proxy administrator.','CometProxyAdmin.owner() points here. The owner can authorize proxy upgrade/admin operations. All four Admin Safe owner addresses are in this seven-owner set.',['upgrade','proxyadmin'],{threshold:4,owners:owners.upgrade,modules:[],moduleDate:'2026-09-21'});
node('tmc','TMC Safe','safe','Treasury Management Committee signing authority.','Controls assets held by this Safe through its signing threshold, and has delegated treasury roles. Governance’s authority over the treasury escrow/timelock must not be confused with ownership of this Safe.',['tmc','treasury','tmc-transparency'],{threshold:4,owners:owners.tmc,modules:[],moduleDate:'2026-09-19'});
node('community','Community Multisig','safe','Proposal Guardian and security authority.','Can cancel unexecuted Governor proposals while its guardian authority is active. This is a human-operated cancellation power, not an automatic distinction between legitimate and malicious proposals. Market pause authority is documented separately.',['community','gov','deployment'],{threshold:5,owners:owners.community});
node('comet','Institutional Comet','contract','Ethereum institutional USDC market proxy.','The current governor is the Admin Safe. getProxyAdmin(comet) identifies CometProxyAdmin as proxy administrator. Launch configuration documents the Community Multisig as pauseGuardian; this getter was not successfully refreshed in the current review.',['comet','proxyadmin','deployment']);
node('config','Configurator','contract','Builds market configurations.','governor() is the Admin Safe; marketAdminPermissionChecker() is the zero address. CometProxyAdmin.getProxyAdmin(configurator) returns the same proxy administrator.',['config','proxyadmin']);
node('proxyadmin','CometProxyAdmin','contract','Institutional upgrade authority.','owner() is the Upgrade Safe. getProxyAdmin() succeeds for both the Comet and Configurator proxies. marketAdminPermissionChecker() is zero.',['proxyadmin']);
node('treasury','Treasury Timelock','contract','Delegated treasury execution with superior governance administration.','The Governor Timelock has DEFAULT_ADMIN_ROLE. TMC has proposer and executor roles; the Community Multisig has a cancellation role. Governance can change subordinate roles through its administrator authority. This is an access-control precedent, not a claim of proxy upgradeability.',['treasury','tmc-transparency'],{roleDate:'2026-09-19; administrator refreshed 2026-09-21'});
node('escrow','Treasury escrow','contract','Treasury custody before withdrawal.','The deployed contract exposes a Timelock-only revoke(tokens, amounts) route returning available escrow assets to the Governor Timelock. It does not recover funds already withdrawn to the TMC Safe or unrelated destinations. Individual token transfers can fail.',['escrow'],{readDate:'2026-09-19'});
node('avatar','Avantgarde Avatar','safe','A Compound-native delegation precedent.','The earlier review found the Treasury Timelock as the single owner (threshold 1). Historical proposals describe limited manager operations through Zodiac Roles. Current role permissions are outside this map’s full audit scope.',['avatar','zodiac','tmc-transparency'],{readDate:'2026-09-19'});
node('controller','Governance controller','proposal','Conceptual ownership and revocation layer — not deployed.','Governance would retain ownership and the ability to replace operators. Operations could be delegated with explicit limits. Upgrade permissions must not allow an operator to remove governance’s superior authority. Requires implementation, security review and migration by existing controllers.',['discussion','zodiac'],{status:'proposed',address:null});
signerRows.forEach(([id,address,label,type,summary,source])=>node(id,label,type,summary,'An owner address contributes toward a Safe’s threshold. It does not unilaterally control the Safe unless it independently meets the required authorization rules.',[...new Set([source,...Object.entries(owners).filter(([,list])=>list.includes(id)).map(([safe])=>safe==='fd947'?'nested':safe)])].filter(Boolean),{address,status:source?'documented':'unknown',identityStatus:source?'documented':'unknown',signer:true,...(id==='fd947'?{threshold:2,owners:owners.fd947}:{}),...(['FC63','d2A7','55be','4A3a','a1bB','9A73'].includes(id)?{human:'Not publicly established in reviewed sources'}:{})}));
node('foundation','Compound Foundation','organization','Documented institutional participant.','Forum descriptions place the Foundation among the Admin and Upgrade Safe institutional constituencies and within the TMC structure. The reviewed sources do not map every relevant owner key to an individual Foundation representative.',['discussion','tmc-mandate'],{status:'documented'});
node('cgwg','CGWG','organization','Governance working group.','Publicly described as Arana Digital and PGov. PGov is a documented Community Multisig signer and coordinator. Exact attribution of compound-dao.eth and the unidentified institutional owner keys remains unresolved.',['cgwg','discussion'],{status:'documented'});
node('security','Security providers','organization','Documented institutional security roles.','ChainSecurity and Certora publicly describe a joint security engagement; both have distinct Community Multisig signer addresses. Institutional market seat descriptions do not establish which unidentified addresses belong to which security personnel.',['ssp','community-list','discussion'],{status:'documented'});

const powersUpdate={
admin:'Institutional Comet governor and Configurator governor. Reviewed core functions include pausing/unpausing market operations, withdrawing available reserves and approveThis(manager,asset,amount), which grants token allowances from Comet. Configurator authority covers market configuration, governor/pause guardian, factories, feeds, extension delegate, rates, reward speeds, collateral settings and permission checker. Stored configuration changes need deployment and an authorized proxy upgrade to take effect in Comet. This is not merely a narrow parameter role; deployed extension routes are not exhaustively audited here.',
upgrade:'Owns CometProxyAdmin, which administers both Institutional Comet and Configurator proxies. Can authorize replacement implementations and proxy administration through that contract. An unrestricted implementation upgrade can change the market’s rules and authorities; it is broader than applying a pre-agreed configuration. All four Admin owner addresses together also satisfy this 4/7 threshold.',
tmc:'4/6 Safe controls its own custody. Holds proposer/executor roles on Treasury Timelock, allowing scheduled operations subject to delay, cancellation and destination permissions. Is tmms on Treasury escrow: initiates withdrawals specifying asset, amount and recipient, and cancels pending requests. Execution after cooldown is permissionless, within the expiry window and only while unpaused. Governance can replace tmms and recover assets still in escrow; this does not recover assets already paid elsewhere. Additional strategy/streamer roles are documented but not fully refreshed.',
community:'5/9 Safe is Governor Proposal Guardian: cancellation of unexecuted proposals while that authority is active. Holds Treasury Timelock cancellation role. Is escrow tsg: can block a pending withdrawal permanently and pause/unpause withdrawal execution; Governor Timelock can also pause/unpause and replace tsg. Institutional Comet pauseGuardian role is documented from deployment, not freshly confirmed by getter. Reviewed Comet core pause method supports both pause and unpause. These are separate permissions, not general ownership of all Compound contracts.',
fd947:'Nested 2/3 Safe is one owner on each of Admin, Upgrade and TMC. Two of its three owner authorizations can provide that single parent-owner authorization. It cannot by itself meet any of those parent thresholds. Two owners have public identity matches (Juan / Juanbug and Abdullah Umar); 0660 remains unattributed. Its organizational mandate is unresolved; the ENS name does not make it Compound Governance.',
avatar:'Observed 1/1 Safe owned by Treasury Timelock. Treasury Timelock-authorized transactions can exercise Safe ownership. Historical Zodiac Roles manager permissions are separate; their current state and the reported strategy deprecation have not been fully re-verified. This is a treasury example, not the Institutional Comet control structure.'};
for(const [id,powers] of Object.entries(powersUpdate)) nodes.find(n=>n.id===id).powers=powers;
nodes.find(n=>n.id==='admin').sources.push('comet-code','config-code');
nodes.find(n=>n.id==='community').sources.push('escrow-code','comet-code');
nodes.find(n=>n.id==='tmc').sources.push('escrow-code');
nodes.find(n=>n.id==='B8Dc').sources.push('juan');
nodes.find(n=>n.id==='3d0e').sources.push('abdullah');

const edges=[];
function edge(from,to,type,label,status,refs,extra={}){edges.push({from,to,type,label,status,sources:refs,...extra});}
edge('gov','timelock','executes-through','executes through','onchain',['gov']);
edge('community','gov','vetoes','can cancel before execution','onchain',['gov']);
edge('timelock','admin','missing-direct-revocation-path','no direct revocation path identified','inferred',['admin','upgrade','comet','proxyadmin','discussion']);
edge('timelock','upgrade','missing-direct-revocation-path','no direct revocation path identified','inferred',['upgrade','proxyadmin','discussion']);
edge('admin','comet','administers','governor','onchain',['comet']);
edge('admin','config','administers','governor','onchain',['config']);
edge('upgrade','proxyadmin','owns','owner','onchain',['proxyadmin']);
edge('proxyadmin','comet','upgrades','proxy administrator','onchain',['proxyadmin']);
edge('proxyadmin','config','upgrades','proxy administrator','onchain',['proxyadmin']);
edge('community','comet','pauses','pause guardian · documented','documented',['deployment']);
edge('timelock','treasury','can-revoke','administrator · can revoke roles','onchain',['treasury']);
edge('tmc','treasury','administers','proposes / executes','onchain',['treasury']);
edge('community','treasury','vetoes','cancels treasury operations','onchain',['treasury']);
edge('timelock','escrow','can-revoke','revoke escrowed assets','onchain',['escrow']);
edge('tmc','escrow','administers','withdrawal authority','onchain',['escrow']);
edge('treasury','avatar','owns','sole Safe owner','onchain',['avatar']);
Object.entries(owners).forEach(([safe,list])=>list.forEach(owner=>edge(owner,safe,'signer-of','owner / signer','onchain',[safe==='fd947'?'nested':safe])));
edge('9A73','cgwg','member-of','member / coordinator','documented',['cgwg']);
edge('4A3a','security','member-of','joint security engagement','documented',['ssp']);
edge('a1bB','security','member-of','joint security engagement','documented',['ssp']);
edge('foundation','admin','documented-seat','institutional constituency; key unresolved','documented',['discussion']);
edge('cgwg','admin','documented-seat','institutional constituency; key unresolved','documented',['discussion']);
edge('security','admin','documented-seat','institutional constituency; key unresolved','documented',['discussion']);
edge('timelock','controller','owns','owns / can replace delegates','proposed',['discussion']);
edge('controller','admin','delegates-to','scoped operational authority','proposed',['discussion']);
edge('controller','upgrade','delegates-to','constrained upgrade authority','proposed',['discussion']);
edge('controller','comet','can-revoke','retains ultimate authority','proposed',['discussion']);
const evidence=[
...['admin','upgrade','tmc','community','fd947'].map(id=>({node:id,date:'2026-09-21',method:'getOwners(); getThreshold()',result:{owners:owners[id].map(s=>signerRows.find(r=>r[0]===s)[1]),threshold:({admin:3,upgrade:4,tmc:4,community:5,fd947:2})[id]},source:id==='fd947'?'nested':id})),
...['admin','upgrade'].map(id=>({node:id,date:'2026-09-21',method:'getModulesPaginated(0x0000000000000000000000000000000000000001, 100)',result:{modules:[],next:'0x0000000000000000000000000000000000000001'},source:id})),
{node:'comet',date:'2026-09-21',method:'governor()',result:A.admin,source:'comet'},
{node:'config',date:'2026-09-21',method:'governor(); marketAdminPermissionChecker()',result:[A.admin,'0x0000000000000000000000000000000000000000'],source:'config'},
{node:'proxyadmin',date:'2026-09-21',method:'owner(); marketAdminPermissionChecker(); getProxyAdmin(comet); getProxyAdmin(configurator)',result:[A.upgrade,'0x0000000000000000000000000000000000000000',A.proxyadmin,A.proxyadmin],source:'proxyadmin'},
{node:'treasury',date:'2026-09-21',method:'hasRole(bytes32(0), GovernorTimelock)',result:true,source:'treasury'},
{node:'gov',date:'2026-09-19',method:'timelock(); proposalGuardian(); proposalGuardianExpiration()',result:[A.timelock,A.community,'1898467200'],source:'gov',note:'Earlier review carried forward; not refreshed on 21 September.'},
{node:'treasury',date:'2026-09-19',method:'hasRole(PROPOSER_ROLE,TMC); hasRole(EXECUTOR_ROLE,TMC); hasRole(CANCELLER_ROLE,Community)',result:[true,true,true],source:'treasury',note:'Earlier review; role-specific refresh date is distinct from administrator refresh.'},
{node:'escrow',date:'2026-09-19',method:'TIMELOCK(); tmms(); tsg(); verified revoke source',result:[A.timelock,A.tmc,A.community],source:'escrow'},
{node:'avatar',date:'2026-09-19',method:'getOwners(); getThreshold()',result:{owners:[A.treasury],threshold:1},source:'avatar'}];
const data={title:'Compound Control Map',version:'2026-09-22.1',chain:{name:'Ethereum',chainId:1},asOf:'2026-09-22',reviewMethod:'Read-only Etherscan contract calls and public primary-source documentation. Values were observed across a review session, not at one pinned block. On-chain verified means the returned state was inspected; it is not a full security audit or independently archived RPC proof.',scope:'Institutional Comet control paths, four principal Safe owner sets, one nested Safe, and selected treasury revocation precedents. No claim to enumerate all Compound wallets or all human relationships.',nodes,edges,sources,evidence,limitations:['No direct Governor revocation route was found through the reviewed governor, proxy-owner, Safe-owner or enabled-module paths. This is a bounded technical conclusion, not proof about every possible external contract, legal remedy or future migration.','On-chain addresses do not identify a human by themselves. Public attribution and on-chain membership are separate evidence layers.','Threshold overlap describes which owner authorizations can satisfy a threshold. It does not prove cooperation, common key custody, misconduct or independence. A Safe owner may itself be a contract.','Five signer addresses lack supported person/organization attribution; compound-dao.eth has an explorer label but its organization remains unresolved. Failed search results are not proof that no public attribution exists.','The Comet pauseGuardian getter did not yield a fresh displayed result in this review. The pause edge is DOCUMENTED from deployment configuration, not marked ON-CHAIN VERIFIED.','The conceptual controller is not implemented, deployed or audited. An unrestricted delegate upgrade route could defeat superior governance authority; a final design must address this explicitly.','Some treasury and Governor readings are carried forward from 19 September and clearly dated in the ledger. Pages linked here can change after this review.','The map does not determine legal duties, proposal legitimacy, liability, or whether a governance resolution is legally binding.']};
fs.writeFileSync(__dirname+'/data.json',JSON.stringify(data,null,2)+'\n');
fs.writeFileSync(__dirname+'/data.js','window.CONTROL_MAP = '+JSON.stringify(data)+';\n');
console.log('Generated '+nodes.length+' nodes, '+edges.length+' edges, '+sources.length+' sources.');
